### ISSUE TITLE
Node Validation

### ISSUE THREAD

**Issue by JoyceBabu** [13twelve/min.js#3]
Node validation function is currently defined as 

  function valid(node){
    return node.nodeType === (1||9||11);
  }

This only performs the check `node.nodeType === 1`.

I think `return [1, 9, 11].indexOf(node.nodeType) > -1` is a cross-browser (except < IE9) alternative that is small.

**Comment by 13twelve** [comment]
Good catch. While thinking about this it also occurred to me that the properties/methods of a node that minjs looks at (className, classList, getAttribute, setAttribute) aren't valid on document or document fragment.

Maybe there is a use case for using the `index` function with document but it seems unlikely to me - I don't think I've ever had a collection of `document` nodes.

I guess this is even simpler:
`return (node.nodeType === 1);`

Updating now. Also merged your pull request, thanks!

**Comment by JoyceBabu** [comment]
Thank you.
